---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-sagemaker-writer
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - models

  - processingjobs

  - trainingjobs

  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - models
  - processingjobs
  - trainingjobs
  verbs:
  - get
  - patch
  - update
